version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      TEST: false
      PORT: 3000
      HOST: localhost
      DATABASE_URL: mongodb://mongo:27017/test
      BORROW_DURATION: 7
      PINO_LOG_LEVEL: debug
      JWT_SECRET: dont-snitch-my-jwt
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
